DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS post;
DROP TABLE IF EXISTS likes;
DROP TABLE IF EXISTS comments;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  profile_picture TEXT NOT NULL,
  about_me TEXT DEFAULT 'Say something'
);

CREATE TABLE post (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  author_id INTEGER NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  title TEXT NOT NULL,
  body TEXT NOT NULL,
  num_likes INTEGER NOT NULL DEFAULT 0,
  user_profile_picture TEXT NOT NULL,
  FOREIGN KEY (author_id) REFERENCES user (id),
  FOREIGN KEY (user_profile_picture) REFERENCES user (profile_picture)
);

CREATE TABLE likes (
  user_id INTEGER NOT NULL,
  post_id INTEGER NOT NULL,
  FOREIGN KEY (user_id) REFERENCES user (id)
  FOREIGN KEY (post_id) REFERENCES post (id)
);

CREATE TABLE comments (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	author_id INTEGER NOT NULL,
	comment TEXT NOT NULL,
	time_posted TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	post_id INTEGER NOT NULL,
  FOREIGN KEY (author_id) REFERENCES user (id)
	FOREIGN KEY (post_id) REFERENCES post (id)
);
